service: ft-shorthand-ceros-publishing

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  role: ${env:AWS_ROLE}
  deploymentBucket: ${env:AWS_DEPLOYMENT_BUCKET}
  environment:
    DEST_BUCKET: ${env:AWS_PROD_BUCKET}
    SOURCE_BUCKET: ${env:AWS_STAGING_BUCKET}

functions:
  main:
    handler: shorthand-ceros/main
    events:
      - s3:
        bucket: ft-shorthand-staging
        event: s3:ObjectCreated:*

package:
  exclude:
    - node_modules/serverless/**
