version: 2.1

orbs:
  node: circleci/node@4.6.0
environment:
  TZ: "Europe/London"
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:14.18-browsers
    steps:
      - checkout
      - node/install-npm:
          version: "8"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate coverage
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          name: Store artifacts (coverage)
          path: coverage/
      - deploy:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = "main" ]
            then
              make deploy
            fi
